### ISSUE TITLE
delete more than one window

### ISSUE THREAD

**Issue by liv-in-sky** [onaralili/SplitUp#12]
hi there,

maybe I'm to stupid to understand how it works but if I mark a couple of tabs - I would like to close this tabs but I can only open a new (splitted) window. ok - I'm able to close the new  window  but it would be great to get the question do you want to delete or split the marked tabs.

in addition sometimes if I try to split the window it will be closed and no other window is appearing. I have to open chromes history to open the window again.

if  I use "save your tabs for later" - where are they - how to open again ?

regards and thanx
armin

**Comment by onaralili** [comment]
hi @liv-in-sky 
About the first point, you are correct. Currently, there is no feature to allow a user to close SELECTED tabs. However, you can close them individually. I am planning to implement in the next version.

About the second and third questions, I am sorry this happened to you. I tried to reproduce the bug but couldn't. Make sure you select at least one tab.
In order to save the tabs and access them later following steps:
1. Use Save  <img width="26" alt="image" src="https://user-images.githubusercontent.com/5898068/46547844-91840780-c8cd-11e8-92f9-c92a8b34d9cf.png"> button on top-right corner of the window.
2. Access them using <img width="30" alt="image" src="https://user-images.githubusercontent.com/5898068/46547885-b37d8a00-c8cd-11e8-8e53-bb5a85415b33.png"> bookmark button on top of the the extension.
Here is a quick animation:
![oct-05-2018 18-34-20](https://user-images.githubusercontent.com/5898068/46547946-e031a180-c8cd-11e8-9b03-eec8b5862d71.gif)

**Comment by liv-in-sky** [comment]
hi  - thanx for you answer

about the bookmark saving. if I select one tab and press the save button - I found the whole window with all tabs in the bookmarks - should it be like this?
![splitup](https://user-images.githubusercontent.com/18462890/46569140-08aeaf80-c951-11e8-87c8-67b162652868.gif)

I don't know if this is important - I use 2 screens and 3 to 4 windows of chrome (canary 64bit)

closing selected tabs:  this is really confusing - please add this!

and I like your crap picture but for new users you should add something like: press here! to split up - otherwise it's only a nice picture (hope you undestand this). I took too long to understand that _ I have to press it

best wishes armin

**Comment by onaralili** [comment]
The features have been implemented. Soon will publish it on the store.
Thanks for the feedback.

**Comment by liv-in-sky** [comment]
I'm curious

**Comment by liv-in-sky** [comment]
hi  - thanx for the implementation   I would like to add some thoughts.

1: if I save one tab to bookmark and later I will bookmark another tab from the same window - I will get a new bookmark entry but seperated - is it possible to sort the bookmarks by opened windows - make this sense?
2: I like the split function - I do a lot of research and it helps a lot to split some tabs to a new window and bookmark it for later. now I know it but for new extension users the crab picture looks like a logo - If it is not possible to add some text like "press here to split" -  would it be possible to change the mouse while "hovering"
3: because of research I have opened about 30 tabs or more in one window. e.g.:if I mark the latest 5 tabs which are on the end of the window I have to scroll down. then I want to bookmark them - I have to scroll up  to the save the tabs - would it be possible to add the bookmark button like the splitup-button
4: would it be possible to have a "select all" in the bookmark window in order to split them all 

thanx armin

**Comment by onaralili** [comment]
Thanks for the feedback.
1. It considers each bookmarked tabs as a session, therefore different sessions are in different windows
2, 3, 4  These ones make sense. Will do something about them in the next version.

**Comment by onaralili** [comment]
@liv-in-sky 2, 4 have been implemented by the contributors. An update will be pubslished today.

- [x] 2: I like the split function - I do a lot of research and it helps a lot to split some tabs to a new window and bookmark it for later. now I know it but for new extension users the crab picture looks like a logo - If it is not possible to add some text like "press here to split" - would it be possible to change the mouse while "hovering"
- [ ] 3: because of research I have opened about 30 tabs or more in one window. e.g.:if I mark the latest 5 tabs which are on the end of the window I have to scroll down. then I want to bookmark them - I have to scroll up to the save the tabs - would it be possible to add the bookmark button like the splitup-button
- [x] 4: would it be possible to have a "select all" in the bookmark window in order to split them all

**Comment by liv-in-sky** [comment]
hi  - thanx for the implementation.

I'm not sure maybe I have already mentioned it: to delete one tab in the bookmark window would be great. is this possible ? it is a little bit confusing. I select a lot of different tabs to bookmark and maybe split somewhere in the future (maybe I close the tabs). the next day I open bookmarks and see that one or two tabs aren't important to me. then I select the two tabs and want to use the basket (delete). but what happens ->all tabs from my session will be deleted. to have the possibility to mark something but the function (delete) is not using this mark is ... if I have deleted the tabs already - I lost all tabs!

thank you and have a good time - armin
